// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppobxxeztmqsqerxzbuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwb2J4eGV6dG1xc3Flcnh6YnV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjEzNzksImV4cCI6MjA2MDg5NzM3OX0.rm-C63fDubG4O9JmiibCWNJ4FLaa6Vyr1lot2M69VtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);